[package]
name = "toggle_i3_titlebar"
version = "0.1.0"
authors = ["Oren Hazi <oren.hazi@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
i3ipc = { version = "0.10.1", features = ["i3-4-14"] }

